# to run the playbook execute: "ansible-playbook -i hosts playbook.yaml -K"
# used -K to prompt for password run as become (root)
# if the user is passwordless then any random password would work.

- name: Main Playbook where all the tasked be called from.
  hosts: dev
  become: yes

  tasks:
    # Calling user management task
    - include_tasks: ./users/manage_users.yml
      vars:
        users:
          - username: mehedi
            state: present # Set to "absent" to delete the user 
            ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}" # public key for ssh
            groups: sudo # to add the use to groups. include 'sudo' to give root access to the user.
            password: '' # if password not given then the user will be passwordless

          - username: user-2
            state: absent # to remove
            ssh_key: "sha-rsa...."
            remove: true # remove home_dir or not when state is absent

    # Install Apache
    - include_tasks: ./install_dependencies/apache2.yml
      vars:
        MODS: [rewrite, ssl, headers, proxy_http, proxy_fcgi]

    # install PHP, its mods, and Composer
    - include_tasks: ./install_dependencies/php.yml 
      vars:
        PHP_VERSION: 8.3
        COMPOSER_VERSION: 2.2.7
        MODS: [fpm, cli, common, mysql, zip, gd, mbstring, curl, xml, bcmath, intl, soap, opcache] 




  handlers:
    - name: start apache2
      service:
        name: apache2
        state: started

    - name: restart apache2
      service:
        name: apache2
        state: restarted

    - name: reload apache2 
      service:
        name: apache2
        state: reloaded

    - name: restart php-fpm
      service: 
        name: php{{ PHP_VERSION }}-fpm
        state: restarted